### ISSUE TITLE
SchemaGrant doesn't work when applied to a specific schema

### ISSUE THREAD

**Issue by benesch** [pulumi/pulumi-snowflake#11]
The following Pulumi program which creates a schema grant on the `test` schema

```py
import pulumi
import pulumi_snowflake as snowflake

db = snowflake.Database("test", name="TEST")
schema = snowflake.Schema("test", database="TEST", name="TEST")
snowflake.SchemaGrant("test",
    database_name="TEST",
    schema_name="TEST",
    privilege="USAGE",
    roles=["FOO"]
)
```

fails with the error:

```
error: snowflake:index/schemaGrant:SchemaGrant resource 'test' has a problem: ConflictsWith: "on_future": conflicts with schema_name. Examine values at 'SchemaGrant.OnFuture'.
```

But the program makes no mention of `on_future`, so it should be valid. I suspect the Pulumi TF bridge is mishandling the `ConflictsWith` declared in the upstream provider.

**Comment by benesch** [comment]
Note that a `SchemaGrant` that specifies `on_future=True` with no schema name _does_ work:

```
snowflake.SchemaGrant("test",
    database_name="TEST",
    privilege="USAGE",
    on_future=True,
    roles=["FOO"]
)
```

**Comment by benesch** [comment]
I think I tracked this down in https://github.com/pulumi/pulumi-terraform-bridge/pull/376.

**Comment by leezen** [comment]
Thanks for providing a fix!

**Comment by cnunciato** [comment]
@leezen Should this be tracked on another board?

**Comment by stack72** [comment]
Hi @benesch 

I am sorry it took a bit to get back to but I just merged in your code from the bridge to this provider and all looks better:

```
import * as snowflake from "@pulumi/snowflake";

const db = new snowflake.Database("test")

const schema = new snowflake.Schema("test", {
    database: db.name,
})

const schemaGrant = new snowflake.SchemaGrant("test", {
    databaseName: db.name,
    schemaName: schema.name,
    privilege: "USAGE",
})
```

```
▶  pulumi up

     Type                            Name                Status
 +   pulumi:pulumi:Stack             snowflake-test-dev  created
 +   ├─ snowflake:index:Database     test                created
 +   ├─ snowflake:index:Schema       test                created
 +   └─ snowflake:index:SchemaGrant  test                created

Resources:
    + 4 created

Duration: 10s
```

I will get a release cut shortly!

**Comment by Josh-a-e** [comment]
:tada: Just wanted to say that I appreciate this having been fixed since I first encountered this issue at lunchtime

**Comment by benesch** [comment]
Thanks very much, @stack72!

**Comment by stack72** [comment]
> Thanks very much, @stack72!

No, thank you for all the work in fixing our bridge :)
