### ISSUE TITLE
Network closed error when trying to run pulumi up

### ISSUE THREAD

**Issue by fadiabassi** [pulumi/pulumi-snowflake#119]
### What happened?

When i try to create my snowflake elements, i'm always getting an error of the connection that was closed ( but when i connect to snowflake UI i can see that those elements were created. 

I'm using python as main language ( i tried many versions of pulumi and always getting the same error).

Here is my script ( which a basic example of creating a db ).

```
import pulumi_snowflake as snowflake

db = snowflake.Database("mydb",
                        comment="created from pulumi", data_retention_time_in_days=1)
```

```
   **_panic: time: missing Location in call to Time.In
    goroutine 99 [running]:
    time.Time.In(...)
        /opt/hostedtoolcache/go/1.17.9/x64/src/time/time.go:1106
    github.com/snowflakedb/gosnowflake.stringToValue(0xc0004fe240, {{0xc000902490, 0xa}, 0x0, 0x0, {0xc0009024a0, 0xd}, 0x0, 0x3, 0x1}, ...)
        /home/runner/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.6.7/converter.go:227 +0xe06**

   error: update failed
  snowflake:index:Database (----):
    error: transport is closing_
```

### Steps to reproduce

The errors occurs when i try to run **pulumi up** for the below basic script

```
import pulumi_snowflake as snowflake

db = snowflake.Database("mydb",
                        comment="created from pulumi", data_retention_time_in_days=1)
```

### Expected Behavior

Database to be created on snowflake a success message should appear on the console

### Actual Behavior

the database is being created when i log onto snowflake ui but on the console it shows me an error that the element was not created

### Versions used
I tried multiple versions and always getting the same error here is the last one i used

CLI
Version      3.27.0
Go Version   go1.17.8
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.6.0
aws-native  0.16.0
command     0.1.0
python      unknown
snowflake   0.8.0

Host
OS       Microsoft Windows 10 Enterprise

This project is written in python

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @fadiabassi 

I am sorry you are getting this error :/ It seems like the provider can't find the timezone locale on your local machine. Are you running this in a container or WSL?

I can see others running in a similar environment have the same problem - https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/945#issuecomment-1077815229

Paul

**Comment by fadiabassi** [comment]
Hello @stack72 ,

I'm running it directly on my windows machine without a container or on a WSL. is there any workaround i can do ?

**Comment by sfc-gh-swinkler** [comment]
the workaround that was mentioned in the other ticket is to set the timezone to UTC for the active user. Please let me know if this resolves your issue.

`alter user <user> set timezone = 'UTC';`

**Comment by fadiabassi** [comment]
It's working thanks
