### ISSUE TITLE
Default role in snowflake.User is ignored

### ISSUE THREAD

**Issue by crisguitar** [pulumi/pulumi-snowflake#153]
### What happened?

I am trying to create a user with a default role. User gets created but the role is not applied.

### Steps to reproduce

```
const gluRole = new snowflake.Role('glu_role', {
	comment: 'Glu role.',
	name: 'glu_role',
});

const gluUser = new snowflake.User('glu', {
	name: 'glu',
	password: myConfig.requireSecret('snowflake-glu-password'),
	defaultRole: gluRole.name, // <= This part is not doing anything
});
```

### Expected Behavior

User is created with default role.

### Actual Behavior

User is created without default role.

### Output of `pulumi about`

```
CLI
Version      3.43.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME       VERSION
aws        5.13.0
docker     3.4.1
nodejs     unknown
snowflake  0.14.0

Host
OS       darwin
Version  12.6
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.8.0'

....
Dependencies:
NAME               VERSION
@types/node        14.18.28
husky              8.0.1
lint-staged        13.0.3
prettier           2.7.1
@pulumi/aws        5.13.0
@pulumi/awsx       0.40.0
@pulumi/pulumi     3.39.3
@pulumi/snowflake  0.14.0

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @crisguitar - the [Snowflake documentation for creating a user](https://docs.snowflake.com/en/sql-reference/sql/create-user.html) does clarify that roles must be granted explicitly:

> Note that specifying a default role for a user does not grant the role to the user. The role must be granted explicitly to the user using the [GRANT ROLE](https://docs.snowflake.com/en/sql-reference/sql/grant-role.html) command. In addition, the CREATE USER operation does not verify that the role exists.

Please let us know if you run into further trouble, but as far as I can tell here, the behavior works as expected.
