### ISSUE TITLE
Ownership grants

### ISSUE THREAD

**Issue by jty-cva** [pulumi/pulumi-snowflake#161]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I can see that ownership grants are only applied to a handful of resources.

For example:
* [RoleOwnershipGrant](https://www.pulumi.com/registry/packages/snowflake/api-docs/roleownershipgrant/) 
* [UserOwnershipGrant](https://www.pulumi.com/registry/packages/snowflake/api-docs/userownershipgrant/)

I'm wondering if there are plans for adding ownership grants to other resources?

It would be very useful for declaring who the owner is for databases, warehouses, schemas, functions, etc.

### Affected area/feature

I suspect it will mean defining new `*OwnershipGrant` files similar to this [RoleOwnershipGrant.py](https://github.com/pulumi/pulumi-snowflake/blob/master/sdk/python/pulumi_snowflake/role_ownership_grant.py). I'd be keen to get some pointers. Thank you.

**Comment by thomas11** [comment]
Hi @jty-cva! Is what you're asking for different from [FunctionGrant](https://www.pulumi.com/registry/packages/snowflake/api-docs/functiongrant/), [DatabaseGrant](https://www.pulumi.com/registry/packages/snowflake/api-docs/databasegrant/), and similar types? Sorry if I misunderstood your question.

**Comment by jty-cva** [comment]
Hi @thomas11 ! Thanks for the response.

I believe they are different because [DatabaseGrant](https://www.pulumi.com/registry/packages/snowflake/api-docs/databasegrant/) grants `PRIVILEGES`. 

Following Snowflake docs, there is a distinction between:
* [Granting privileges](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege.html)
* [Granting ownership of a resource](https://docs.snowflake.com/en/sql-reference/sql/grant-ownership.html)

I could be wrong, I don't think this will work:

```
grant = snowflake.DatabaseGrant("grant",
    database_name="db",
    privilege="OWNERSHIP", # ownership is not a privilege
    roles=[
        "role1",
        "role2", # ownership can only be given to one role, a list is not the right type
    ],
    shares=[
        "share1",
        "share2",
    ],
    with_grant_option=False)
```

**Comment by thomas11** [comment]
Hey @jty-cva, I haven't used the Snowflake provider myself but it seems that "OWNERSHIP" is actually a valid privilege. See, for instance, the [SchemaGrant](https://www.pulumi.com/registry/packages/snowflake/api-docs/schemagrant/#inputs) docs. It could be that `roles` should then only have a length of 1, I'd need to verify that separately. Maybe you could try it out? Thanks!

**Comment by jty-cva** [comment]
Thanks let me get back to you on this!

**Comment by jty-cva** [comment]
I can confirm the ownership grants work for databases, schemas, and warehouses. If privilege is set to `OWNERSHIP`, they perform the `grant ownership` action. 

Closing this now.
