### ISSUE TITLE
Snowflake database not accesible

### ISSUE THREAD

**Issue by jandroav** [pulumi/pulumi-snowflake#164]
I am building a CLI to handle Snowflake databases using the [Automation API inline](https://www.pulumi.com/docs/guides/automation-api/) program mode for Golang. 

The code is taken from [this example](https://www.pulumi.com/registry/packages/snowflake/api-docs/database/) and adapted as:

```go
	fmt.Println(color.Colorize(color.Yellow, "Creating/checking SnowFlake database instance..."))
	var defaultShortUUID string = genShortUUID()
	deployDataBaseFunc := func(ctx *pulumi.Context) error {
		_, err := snowflake.NewDatabase(ctx, cm.RESOURCE_TAG+dbName, &snowflake.DatabaseArgs{
			Name:                    pulumi.String(cm.RESOURCE_TAG + dbName + "_" + defaultShortUUID),
			Comment:                 pulumi.String("Created by Jarvis"),
			DataRetentionTimeInDays: pulumi.Int(1),
		})
		if err != nil {
			return err
		}
[....]
    return executePulumiFunction(deployDataBaseFunc, destroy)
```

The database is correctly created but not accessible, getting a `Cannot perform CREATE TABLE. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.` when connecting to it.

I am using the same Snowflake user and password to create databases from Pulumi and from the Snowflake UI.

Example created from Pulumi:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/67458478/203158314-edc038c7-82cf-4db1-9acc-936c54828e67.png">

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/67458478/203158743-c1e1706f-5610-44d2-93e7-301e4ba5dcf5.png">

Example created from the Snowflake UI:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/67458478/203158423-645b71d5-78e1-4ee9-8b0e-cfb9419353ce.png">

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/67458478/203158698-a212a0e6-7ca1-49b7-ba12-fea76313ffc5.png">

It seems like the creation from Pulumi is missing something, or some other initialization may happen.

Here is the Pulumi resource:

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/67458478/203158633-2b0a24a3-63b8-451f-812b-1b310997b0b5.png">

I am missing something when creating the Snowflake database resource?

**Comment by guineveresaenger** [comment]
Hi @jandroav -

could you let us know the output of `pulumi about` in your project folder?

**Comment by jandroav** [comment]
Hi @guineveresaenger !

As I am using Pulumi in an inline way I don't have a `Pulumi.yaml` in my project folder but the output is the following:

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/67458478/203244475-55455d15-8cb4-482a-9899-e1335ffd5cf7.png">

I am attaching here the scrubbed output generated from the Pulumi service when creating the resource:

```json
{
  "version": 3,
  "deployment": {
    "manifest": {
      "time": "2022-11-22T07:42:36.553494+01:00",
      "magic": "2d188b4b8e68bd30f127471b3d597459b26fe3603e3a668d8fc3131995cf292d",
      "version": "v3.47.1"
    },
    "secrets_providers": {
      "type": "service",
      "state": {
        "url": "https://api.pulumi.com",
        "owner": "jandroav",
        "project": "jarvis",
        "stack": "jandro"
      }
    },
    "resources": [
      {
        "urn": "urn:pulumi:jandro::jarvis::pulumi:pulumi:Stack::jarvis-jandro",
        "custom": false,
        "type": "pulumi:pulumi:Stack"
      },
      {
        "urn": "urn:pulumi:jandro::jarvis::pulumi:providers:snowflake::default",
        "custom": true,
        "id": "9b77e8c9-ea17-4f6d-9f64-5fd42595c787",
        "type": "pulumi:providers:snowflake",
        "inputs": {
          "account": "fk56316",
          "password": "",
          "region": "eu-west-3.aws",
          "username": "jarvis"
        },
        "outputs": {
          "account": "fk56316",
          "password": "",
          "region": "eu-west-3.aws",
          "username": "jarvis"
        }
      },
      {
        "urn": "urn:pulumi:jandro::jarvis::snowflake:index/database:Database::jarvis_trips",
        "custom": true,
        "id": "jarvis_trips_812787e0",
        "type": "snowflake:index/database:Database",
        "inputs": {
          "__defaults": [
            "isTransient"
          ],
          "comment": "Created by Jarvis",
          "dataRetentionTimeInDays": 1,
          "isTransient": false,
          "name": "jarvis_trips_812787e0"
        },
        "outputs": {
          "comment": "Created by Jarvis",
          "dataRetentionTimeInDays": 1,
          "id": "jarvis_trips_812787e0",
          "isTransient": false,
          "name": "jarvis_trips_812787e0"
        },
        "parent": "urn:pulumi:jandro::jarvis::pulumi:pulumi:Stack::jarvis-jandro",
        "provider": "urn:pulumi:jandro::jarvis::pulumi:providers:snowflake::default::9b77e8c9-ea17-4f6d-9f64-5fd42595c787",
        "propertyDependencies": {
          "comment": null,
          "dataRetentionTimeInDays": null,
          "name": null
        }
      }
    ]
  }
}
```

**Comment by guineveresaenger** [comment]
A quick thought - does your database perhaps need privileges? 
https://www.pulumi.com/registry/packages/snowflake/api-docs/databasegrant/

What you're seeing lines up with [fSnowflake forum answers around insufficient access privileges](https://community.snowflake.com/s/question/0D50Z00009a7Ur4SAE/why-im-getting-sqlalchemyexcprogrammingerror-snowflakeconnectorerrorsprogrammingerror-090105-22000-cannot-perform-create-table-this-session-does-not-have-a-current-database-call-use-database-or-use-a-qualified-name).

**Comment by jandroav** [comment]
Hi @guineveresaenger 

It seems there is an issue with uppercase and lowercase when setting the database name. Snowflake is supposed to pass the database name in double quotes if we do not want to change the name to UPPERCASE otherwise snowflake will take the object name in upper case:

https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html#identifier-requirements

I am trying to connect to the database through JDBC and it is supplying the database name in lowercase but Snowflake will take it as uppercase only. There is a parameter [QUOTED_IDENTIFIERS_IGNORE_CASE](https://docs.snowflake.com/en/sql-reference/parameters.html#label-quoted-identifiers-ignore-case) to control this behavior but it seems it can not be set through JDBC URi parameters.

https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html#label-identifier-casing-parameter-howto

So my fix was creating the database from Pulumi in uppercase.

**Comment by guineveresaenger** [comment]
Ah! Thank you for the find! I'm glad you found a fix. I'll close this issue for now then. Feel free to reopen if you have further concerns. 🎉
