### ISSUE TITLE
Support configuring provider via environment variables such as `SNOWFLAKE_ACCOUNT`

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-snowflake#167]
Provider documentation references environment variables such as `SNOWFLAKE_ACCOUNT`, `SNOWFLAKE_REGION`, etc., however the Snowflake provider info declaration lacks env var configuration options:

https://github.com/pulumi/pulumi-snowflake/blob/715bcd64af319393bf6e807a2478ebc224cf0132/provider/resources.go#L78

This results in an error when using a partially configured provider resource:

```py
security_admin = snowflake.Provider('security_admin',
    role='SECURITYADMIN',
)
```

Erroring with: `TypeError: Missing required property 'account'`

To improve on this, we should supply a `Config` block that maps provider inputs to environment variables, as other providers such as DigitalOcean do here: 

https://github.com/pulumi/pulumi-digitalocean/blob/86a848d4f38c4999b91a027cffe425f9cf4aba96/provider/resources.go#L77-L89

**Comment by jkodroff** [comment]
This was fixed in https://github.com/pulumi/pulumi-snowflake/pull/223 and I've verified that it works in my own Pulumi program.

**Comment by AaronFriel** [comment]
Thanks for confirming @jkodroff!
