### ISSUE TITLE
Registry docs not being published

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-snowflake#173]
The [registry docs](https://www.pulumi.com/registry/packages/snowflake/) show v0.14.0, although [v0.15.0](https://github.com/pulumi/pulumi-snowflake/releases/tag/v0.15.0) was published last week and the docs creation step ran.

Similar to pulumi/pulumi-civo#174?

**Comment by susanev** [comment]
relevant?
https://github.com/pulumi/registry/actions/runs/3877205366/jobs/6611945801

civo has a similar error

**Comment by guineveresaenger** [comment]
Fixed via https://github.com/pulumi/registrygen/pull/15
and https://github.com/pulumi/registry/pull/1911
