### ISSUE TITLE
snowflake provider not retrieving RoleGrants

### ISSUE THREAD

**Issue by dmorel** [pulumi/pulumi-snowflake#177]
### What happened?

I have several users and roles granted the ACCOUNTADMIN role like this:

`show grants of role ACCOUNTADMIN;`

<output redacted>

```
role          granted_to  grantee_name
------------  ----------  ---------------------
ACCOUNTADMIN  USER        ******
ACCOUNTADMIN  ROLE        PULUMI_ROLE
ACCOUNTADMIN  USER        *****************.com
ACCOUNTADMIN  USER        ***********.com
ACCOUNTADMIN  USER        *************.com
ACCOUNTADMIN  USER        ************.com
ACCOUNTADMIN  USER        ***************.com
```

when importing, I expect the following command to pull in the roles mentioned above:

`pulumi import --diff snowflake:index/roleGrants:RoleGrants ACCOUNTADMIN ACCOUNTADMIN`

but the result is disappointing:

```
  accountadmin = snowflake.RoleGrants(
    "ACCOUNTADMIN", 
    role_name="ACCOUNTADMIN",
    opts=pulumi.ResourceOptions(protect=True))
```

### Expected Behavior

```
  accountadmin = snowflake.RoleGrants(
    "ACCOUNTADMIN", 
    role_name="ACCOUNTADMIN",
    roles = [ list of roles ],
    users = [ list of users ],
    opts=pulumi.ResourceOptions(protect=True))
```

### Steps to reproduce

- create roles and users
- grant them the ACCOUNTADMIN role
- run import

### Output of `pulumi about`

```
CLI
Version      3.52.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.28.0
aws-native  0.45.0
datadog     4.13.0
python      unknown
random      4.8.2
snowflake   0.15.0

Host
OS       darwin
Version  13.1
Arch     arm64

This project is written in python: executable='/Users/dmorel/Library/Caches/pypoetry/virtualenvs/***-py3.10/bin/python3' version='3.10.8'

Current Stack: seenons/snowflake/prod

TYPE                                         URN
pulumi:pulumi:Stack                          urn:pulumi:prod::snowflake::pulumi:pulumi:Stack::snowflake-prod
pulumi:providers:snowflake                   urn:pulumi:prod::snowflake::pulumi:providers:snowflake::default_0_15_0
[...]
snowflake:index/roleGrants:RoleGrants        urn:pulumi:prod::snowflake::snowflake:index/roleGrants:RoleGrants::DBT_ROLE_PROD
snowflake:index/roleGrants:RoleGrants        urn:pulumi:prod::snowflake::snowflake:index/roleGrants:RoleGrants::ANALYST
snowflake:index/roleGrants:RoleGrants        urn:pulumi:prod::snowflake::snowflake:index/roleGrants:RoleGrants::AIRBYTE_ROLE
snowflake:index/roleGrants:RoleGrants        urn:pulumi:prod::snowflake::snowflake:index/roleGrants:RoleGrants::ACCOUNTADMIN
snowflake:index/roleGrants:RoleGrants        urn:pulumi:prod::snowflake::snowflake:index/roleGrants:RoleGrants::SYSADMIN


Found no pending operations associated with prod

Backend
Name           pulumi.com
URL            https://app.pulumi.com/dmorel
User           dmorel
Organizations  dmorel, seenons

Dependencies:
NAME               VERSION
black              22.12.0
coloredlogs        15.0.1
flake8             6.0.0
fqdn               1.5.1
isoduration        20.11.0
jsonpointer        2.3.0
jupyter            1.0.0
pip                22.3.1
pulumi-aws         5.28.0
pulumi-aws-native  0.45.0
pulumi-datadog     4.13.0
pulumi-random      4.8.2
pulumi-snowflake   0.15.0
setuptools         65.6.3
toml               0.10.2
uri-template       1.2.0
webcolors          1.12.0
wheel              0.38.4
yapf               0.32.0

Pulumi locates its logs in /var/folders/vl/p5nzjtzn6ss46n6xmz9rpnlh0000gn/T/ by default
```

### Additional context

initial discussion on https://pulumi-community.slack.com/archives/C84L4E3N1/p1674833299507689

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dmorel** [comment]
The funny thing is this applies only to import: creating the resource works, and state is checked correctly on the database: I just tried removing one of the granted users from the list directly in snowflake, and the next execution of pulumi up showed the correct diff with just one username, and restored them properly. So my assumption is I can trust the resource, only not the import.

**Comment by AaronFriel** [comment]
@dmorel Thanks for reporting this, I think this was a change in the upstream provider. The import operation defined by Snowflake only reads roles and users previously created by the provider.
 
I've filed an issue here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1499

**Comment by AaronFriel** [comment]
I'll keep this open, as it is "by-design" but also blocked on an upstream change.

**Comment by aq17** [comment]
Hi @dmorel , this issue should be resolved now with the latest `pulumi-snowflake` releases >`v.0.17.0`

**Comment by aq17** [comment]
Going to close as completed for now if no further comment.
