### ISSUE TITLE
[Snowflake] support for database roles

### ISSUE THREAD

**Issue by derence-boxed** [pulumi/pulumi-snowflake#201]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

snowflake has introduced DATABASE ROLES that facilitate data sharing in a much more convenient way: 
https://docs.snowflake.com/en/sql-reference/sql/create-database-role.html

Can Pulumi release new API to support for DATABASE ROLE?

**Comment by aq17** [comment]
Hi @derence-boxed , we should be able to support this once Snowflake officially releases it in their provider.

**Comment by AaronFriel** [comment]
We're tracking:
- https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1442
- https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1654

**Comment by sicarul** [comment]
This is now supported, e.g.:

```
new snowflake.DatabaseRole("DBRole", { database: 'MyDB', name: "MyDBRole"})
```
