### ISSUE TITLE
[Snowflake] Handle grantee type database_roles

### ISSUE THREAD

**Issue by derence-boxed** [pulumi/pulumi-snowflake#202]
### What happened?

In case when the permission is granted outside Pulumi to a database role in snowflake, the planning stage will fail with "unknown grantee - DATABASE_ROLES"

### Expected Behavior

Understand that database role is an open feature in Snowflake for now, I'd expect Pulumi to ignore these grantees for now until the GA of this feature on Snowflake, followed by a proper API to address this grantee 

### Steps to reproduce

1. Use a grant API, such as schemaGrant to grant some permission (say usage or monitor) on a schema to some roles
2. Create a new database role in Snowflake (outside Pulumi) and grant the similar permission as step 1
3. The next Pulumi preview or Pulumi up will fail at planning stage with the error "Unknown grantee type DATABASE_ROLE"

### Output of `pulumi about`

CLI          
Version      3.50.2
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME           VERSION
aws            5.1.0
command        0.7.0
datadog        4.12.0
docker         3.1.0
ec             0.3.0
fastly         5.1.0
gcp            6.12.0
github         5.1.0
google-native  0.14.0
kubernetes     3.23.0
kubernetes     3.16.0
mongodbatlas   3.5.2
nodejs         unknown
opsgenie       1.1.9
postgresql     3.6.0
random         4.3.1
snowflake      0.18.0
snowflake      0.5.2
terraform      5.6.7
tls            4.1.0

Host     
OS       alpine
Version  3.17.0
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v18.12.1'

### Additional context

Open a feature request ticket for long term solution: https://github.com/pulumi/pulumi-snowflake/issues/201

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hi @derence-boxed , thanks for opening this issue. It appears it may be related to [this other issue](https://github.com/pulumi/pulumi-snowflake/issues/177) – would you mind taking a look and also provide a repro if that doesn't help?

**Comment by aq17** [comment]
Going to close this as stale since there have been a few provider releases since – please reopen if there are any further questions/ issues
