### ISSUE TITLE
bug: IDP authentication issue with connection to snowflake using state rather than config

### ISSUE THREAD

**Issue by hexDoor** [pulumi/pulumi-snowflake#212]
### What happened?

My colleagues inform me that this didn't occur until recently but we are running into issues running `destroy` pulumi commands when attempting to destroy snowflake resources.

We run into the following error message:
```
* error deleting masking policy ***: 390191 (08004): The user you were trying to authenticate as differs from the user currently logged in at the IDP.
```

This issue occurs when a different snowflake user (eg. `worker2@company.com`) attempts to destroy resources created by (eg. `worker1@company.com`) another user despite both users utilising the same role (eg. `warehouse_manager`).
We tested with a third user and they also run into the same issue. 

We are able to verify this by checking our snowflake login history which reports the error to be a result of `USERNAME_MISMATCH`.

### Expected Behavior

We should not be seeing an error.

### Steps to reproduce

Upon further analysis of a created resource such as `masking_policy` and the relevant pulumi state file, we notice some `input` and `output` values from the `provider` state which have always been around but which I suspect is causing the issue.
```
"inputs": {
        "account": "***",
        "browser_auth": "true",
        "region": "us-east-1",
        "role": "WAREHOUSE_MANAGER",
        "username": "WORKER1@COMPANY.COM",
        "version": "0.20.0",
        "warehouse": "***"
},
"outputs": {
        "account": "***",
        "browser_auth": "true",
        "region": "us-east-1",
        "role": "WAREHOUSE_MANAGER",
        "username": "WORKER1@COMPANY.COM",
        "version": "0.20.0",
        "warehouse": "***"
}
```

With some experimentation, we have discovered that if we modify the `username` to match the configured `SNOWFLAKE_USER` env variable who is executing the `destroy` command, the IDP issue disappears.

As a result, we suspect that pulumi is utilising the state file to generate it's connection configuration to snowflake rather than the configuration passed to `pulumi` via environment variables.

To make the necessary change. we currently have two workarounds with both being equally terrible in their long term suitability which is effectively blocking our project:

1. Run `pulumi up` before running `destroy`
    - Assuming that the resource configuration has not changed, pulumi will report that the resources are unchanged
    - However, the state file will change the `username` in the aforementioned code block to be the value in `SNOWFLAKE_USER` environment variable
    - As such, this makes the aforementioned change which will solve the IDP issue
    - We don't think we should be running `up` in any case for a `destroy` action
    - `pulumi refresh` does not work as we run into the IDP issue
2. Regular Expression Replace
    - We thought that this might not be a bad idea but we could see very strange behaviour when doing this with certain resources so we immediately ruled this out even though it does fix the issue

### Output of `pulumi about`

CLI
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Host
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in python: executable='/nix/***/bin/python3' version='3.8.12
'

Current Stack: ***

Note: *** refers to masked information

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@hexDoor Could you provide a minimal Pulumi program for us to reproduce this? It'll be helpful for us to report this on the upstream provider as well.

And does this issue occur with resources aside from `masking_policy`? It isn't clear from the state file if you've copied the provider state or a Snowflake resource's.

**Comment by hexDoor** [comment]
Hi @AaronFriel.

I'll see what I can do with the minimal example as I am currently inundated with other work and some processes to make it happen but will try to get this to you soon.
(Either before today or tomorrow CoB AEST)

For clarification, our workflow has us split the resource types into their own stacks.
I took another look and the aforementioned configuration is the `provider` state.
(I will make that clarification in the issue ticket as well)

With that in mind, the terraform workflow requires a separate provider resource per user but i'm not sure if that is relevant.

**Comment by hexDoor** [comment]
Hi @AaronFriel,

Please see the following as the minimal repro example with `role` resource although the issue is within the `provider` resource (`pulumi:providers:snowflake::default_0_20_0`):

I have placed notes and commenting throughout our program to provide further context and clarification.

## handler.py
```py
from pathlib import Path
import pulumi.automation as auto
import pulumi_snowflake as snowflake


def pulumi_program():
    snowflake.Role(
        resource_name="IDP_TEST_ROLE",  # An ID is a unique identifier
        name="IDP_TEST_ROLE",  # The name is the name of the Snowflake object. It must be uppercased.
    )


def main(action: str, user: str):
    work_dir = Path(Path(__file__).parent.absolute())
    workspace = auto.LocalWorkspace(work_dir=work_dir)

    print(f"Workspace dir: {workspace.work_dir}")

    account_name = "***" # REPLACE THIS WITH ACCOUNT_NAME
    project_name = "***" # REPLACE THIS WITH PROJECT_NAME
    stack_name = f"{account_name}.example__idp__repro.roles"
    region = "***" # REPLACE THIS WITH AWS REGION
    snowflake_user = user.upper()
    snowflake_role = "***" # REPLACE THIS WITH ROLE
    snowflake_warehouse = "***" # REPLACE THIS WITH WAREHOUSE

    print("Creating stack...")
    stack = auto.create_or_select_stack(
        stack_name=stack_name, project_name=project_name, program=pulumi_program
    )
    stack.set_config("snowflake:account", auto.ConfigValue(value=account_name))
    # NOTE: OUR WORKFLOW AUTHENTICATES TO SNOWFLAKE VIA OKTA SAML SSO
    # IT HAS BEEN VERIFIED THAT OKTA IS RETURNING THE CORRECT SAML RESPONSE
    # RETURNS SAML AUTHENTICATION RESPONSE FOR USER DEFINED AS user VARIABLE IN THIS FUNCTION
    stack.set_config("snowflake:browser_auth", auto.ConfigValue(value="true"))
    stack.set_config("snowflake:region", auto.ConfigValue(value=region))
    stack.set_config("snowflake:username", auto.ConfigValue(value=snowflake_user.upper()))
    stack.set_config("snowflake:role", auto.ConfigValue(value=snowflake_role.upper()))
    stack.set_config("snowflake:warehouse", auto.ConfigValue(value=snowflake_warehouse.upper()))

    print("Stack setup...")
    print(f"Performing action: {action}")

    if action == "up":
        stack.up(parallel=1)
    elif action == "destroy":
        stack.destroy(parallel=1)


# SETUP SNOWFLAKE RESOURCES
main("up", "main_user@company.com")

# THIS RESULTS WITH ERROR.LOG OUTPUT
# NOTE: BOTH USERS HOLD THE SAME ROLE WHICH SHOULD
# ALLOW BOTH USERS TO TAKE DOWN RESOURCES
main("destroy", "diff_user@company.com")
# THIS COMMAND WORKS FINE
main("destroy", "main_user@company.com")
```

## error.log
```
    pulumi:pulumi:Stack ***-***.example__idp__repro.roles  time="***" level=error msg="Authentication FAILED" func="gosnowflake.(*defaultLogger).Errorln" file="log.go:242"
 -  snowflake:index:Role IDP_TEST_ROLE deleting (3s) error: deleting urn:pulumi:***.example__idp__repro.roles::***::snowflake:index/role:Role::IDP_TEST_ROLE: 1 error occurred:
 -  snowflake:index:Role IDP_TEST_ROLE **deleting failed** error: deleting urn:pulumi:***.example__idp__repro.roles::***::snowflake:index/role:Role::IDP_TEST_ROLE: 1 error occurred:
    pulumi:pulumi:Stack ***-***.example__idp__repro.roles  error: update failed
    pulumi:pulumi:Stack ***-***.example__idp__repro.roles **failed** 1 error; 1 message

Diagnostics:
  snowflake:index:Role (IDP_TEST_ROLE):
    error: deleting urn:pulumi:***.example__idp__repro.roles::***::snowflake:index/role:Role::IDP_TEST_ROLE: 1 error occurred:
    	* 390191 (08004): The user you were trying to authenticate as differs from the user currently logged in at the IDP.

  pulumi:pulumi:Stack (***-***.example__idp__repro.roles):
    error: update failed

    time="***" level=error msg="Authentication FAILED" func="gosnowflake.(*defaultLogger).Errorln" file="log.go:242"
```

**Comment by AaronFriel** [comment]
@hexDoor Thank you for the repro! It does look like this could be an upstream issue in how the provider handles the user changing - is it possible to omit the username property in your stack config and the browser auth/OAuth will take care of determining the user ID?

If not, we'll take a look at finding or filing an issue upstream to address this. 

As an aside, kudos for the example using automation API!

**Comment by hexDoor** [comment]
@AaronFriel No Worries!

Unfortunately, leaving `username` unset in the stack config does no work out of the box:
```
Diagnostics:
  snowflake:index:Role (IDP_TEST_ROLE):
    error: 1 error occurred:
    	* missing required configuration key "snowflake:username": Username for username+password authentication. Can come from the `SNOWFLAKE_USER` environment variable.
    Set a value using the command `pulumi config set snowflake:username <value>`.
```

Would you be able to file the issue upstream and I'll see if I can contribute a fix to it once I get a better understanding of how the provider works?

Perhaps I can try to make a PR since this issue is blocking our project.

**Comment by AaronFriel** [comment]
@hexDoor If I had to guess, the provider is not updating its config from environment variables on each run, and is keeping - as if cached - the username between subsequent executions.

It's possible we could fix this in our own provider. Let me look into that.

**Comment by AaronFriel** [comment]
@hexDoor We'll review PR #214, and once we make a release with that, I'd like you to try that out.
- https://github.com/pulumi/pulumi-snowflake/pull/214

I think the issue might be that we are not configuring the default provider with fresh username config on each execution. If that's not the issue, I'll confer back with the team.

**Comment by hexDoor** [comment]
@AaronFriel Thanks for working so quickly.
From where we stand, this PR should solve the issue for us but i'll note some questions on the PR itself.

**Comment by hexDoor** [comment]
Unfortunately https://github.com/pulumi/pulumi-snowflake/pull/223 does not solve this issue as it's a fundamental upstream issue.
It'll require radical changes on the terraform snowflake provider that this package implements an adapter to so our team has decided to proceed with a workaround by managing resources under a single service user.
