### ISSUE TITLE
Add examples for `snowflake.StorageIntegration` to documentation

### ISSUE THREAD

**Issue by kongwilson** [pulumi/pulumi-snowflake#253]
Hi, as we are building our IAC for sources we need to ingest data to Snowflake using Snowpipe, we found that it seems StorageIntegration is not yet supported in `pulumi_snowflake` as shown in the screenshot
<img width="846" alt="image" src="https://github.com/pulumi/pulumi-snowflake/assets/12696650/1175ac89-2fe7-4101-9f93-72d751f7b0b1">

I would like to raise such an issue so keep track on the latest development of such support. 

Thanks.

**Comment by aq17** [comment]
Hi @kongwilson , thanks for opening up this issue. Apologies for the misleading docs – this resource should be fully supported in the pulumi provider. We'll track progress on this issue, but you should be able to use the resource now.
Please let us know if you have any further questions.

**Comment by kongwilson** [comment]
Thanks @aq17 , I will give it a go:)

**Comment by kongwilson** [comment]
It does exist and works well. Thanks
