### ISSUE TITLE
Error: 260002: password is empty

### ISSUE THREAD

**Issue by srivya** [pulumi/pulumi-snowflake#489]
### What happened?

plum-snowflake version
0.48.0/0.47.0

on Mac OS  Ventura (13.3.1)

Describe the bug 
it requires a password field even when using private key path option

* 260002: password is empty

There does seem to be an open issue in the upstream package.
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2169

There seems to be work around by using `authenticator` :https://github.com/Snowflake-Labs/terraform-provider-snowflake/commit/bd72c055f68e50aea235c78fce5602d87abfef22

Can we expose that option while setting up authentication?

Expected behavior
No error

### Example

Diagnostics:
  snowflake:index:Schema (Test_Schema):
    error: 1 error occurred:
        * 260002: password is empty

  pulumi:pulumi:Stack (snowflake-prd-snowflake):
    warning: provider config warning: use the [file Function](https://developer.hashicorp.com/terraform/language/functions/file) instead

### Output of `pulumi about`

CLI          
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME       VERSION
gcp        6.67.1
github     4.17.0
python     unknown
snowflake  0.47.0

Host     
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in python: executable='/Users/yashsrivastava/de_utils/venv/bin/python3' version='3.8.15
'

Backend        
Name           Yashs-MacBook-Pro.local
URL            gs://production-pulumi/
User           yashsrivastava
Organizations  

Dependencies:
NAME                                   VERSION
build                                  1.0.3
bump2version                           1.0.1
ce-de-utils                            0.0.80
coverage                               7.4.1
dbt-snowflake                          1.7.1
doq                                    0.10.0
grpcio-status                          1.60.0
ipdb                                   0.13.13
keyrings.google-artifactregistry-auth  1.1.2
msgpack                                1.0.7
pip                                    22.0.4
pre-commit                             3.5.0
pulumi-gcp                             6.67.1
pulumi-github                          4.17.0
pulumi_snowflake                       0.47.0
twine                                  4.0.2
wheel                                  0.42.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @srivya. Thanks for filing an issue and associating it with an associated upstream issue. If the upstream provider supports an authenticator field, then we should to. Why do you think we don't?
