### ISSUE TITLE
Connection caching for external browser authentication

### ISSUE THREAD

**Issue by anitalySuper** [pulumi/pulumi-snowflake#517]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

While using the snowflake provider with externalbrowser authentication, hundreds of tabs are opened in the browser as it re-authenticates for every resource being planned/previewed or imported. This makes the provider very hard to use with externalbrowser authentication.

Same issue in terraform-snowflake-provider https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1700

### Affected area/feature

pulumi-snowflake

**Comment by iwahbe** [comment]
Hi @anitalySuper. Thanks for reporting this issue here. This provider is actually a projection of the Snowflake's TF provider, so we will resolve this as soon as they do.

**Comment by bschwedler** [comment]
I can confirm that this now works.

To get this to work, it requires the following setup:

- https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use#using-connection-caching-to-minimize-the-number-of-prompts-for-authentication-optional
- ` SNOWFLAKE_CLIENT_STORE_TEMPORARY_CREDENTIAL=1`

**Comment by iwahbe** [comment]
Thanks for reporting that @bschwedler.
