### ISSUE TITLE
False positive updates on table fields

### ISSUE THREAD

**Issue by sicarul** [pulumi/pulumi-snowflake#572]
### What happened?

Snowflake will automatically convert fields to its internal representation, STRINGs are saved as "VARCHAR(16777216)", TIMESTAMP_NTZs are saved as "TIMESTAMP_NTZ(9)", if you do not use the exact names as represented in the Database, the table creation will work, but every subsequent update will try to update it again to "correct" the types to what is in the pulumi program.

### Example

Example: Create a table with column types STRING and TIMESTAMP_NTZ, and when you update after table creation, you'll see it tries to update it again:

<img width="929" alt="image" src="https://github.com/pulumi/pulumi-snowflake/assets/4952116/6729d25a-7f83-4635-9007-3e0d9b69449c">

The operation is harmless but it shows up as an update each time even though nothing is happening

### Output of `pulumi about`

CLI
Version      3.111.1
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME       VERSION
aws        5.32.0
awsx       1.0.2
docker     3.6.1
nodejs     unknown
random     4.12.0
snowflake  0.18.1

Host
OS       darwin
Version  14.4.1
Arch     arm64

This project is written in nodejs: executable='/Users/pabloseibelt/.nvm/versions/node/v18.6.0/bin/node' version='v18.6.0'

Current Stack: pulumi/dwh-workflows-loader-cdcbuckets/production

[Truncated resources]

Found no pending operations associated with pulumi/production

Backend
Name           pulumi.com
URL            https://app.pulumi.com/v-pablo-pulumi-corp
User           v-pablo-pulumi-corp
Organizations  v-pablo-pulumi-corp, pulumi
Token type     personal

Dependencies:
NAME               VERSION
@pulumi/random     4.12.0
@pulumi/snowflake  0.18.1
@types/node        16.18.18
@pulumi/aws        5.32.0
@pulumi/awsx       1.0.2
@pulumi/pulumi     3.58.0

Pulumi locates its logs in /var/folders/0g/n3hrlpn56jb72cnjwggcy3kh0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
I opened a bug upstream with a full repro in terraform: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2733

**Comment by mikhailshilkov** [comment]
The upstream issue has been closed, so I'm closing this one too
