### ISSUE TITLE
Rendering/Styling issue with API Docs

### ISSUE THREAD

**Issue by bschwedler** [pulumi/pulumi-snowflake#683]
### Describe what happened

Many of the Resources under the [API Docs](https://www.pulumi.com/registry/packages/snowflake/api-docs/) are not rendering properly.

It does not seem to matter which language is selected.
I have reproduced this in Firefox, Chromium, & Google Chrome

![Database](https://github.com/user-attachments/assets/ebe50b5a-223b-4202-b67f-048c55ad59c1)

![AccountRole](https://github.com/user-attachments/assets/639ff4d5-f8a3-480d-915c-41d918c23905)

### Sample program

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @bschwedler, thanks for opening this issue. I'll take a look later this week.

**Comment by guineveresaenger** [comment]
Related: https://github.com/pulumi/registry/issues/4856

**Comment by sean1588** [comment]
@iwahbe here are other pages I have identified with this issue based on the new tests for the API docs pages I stood up which should now be reporting into metabase. We should verify these get addressed as well.

**Snowflake:**
https://www.pulumi.com/registry/packages/snowflake/api-docs/database/
https://www.pulumi.com/registry/packages/snowflake/api-docs/networkpolicy/
https://www.pulumi.com/registry/packages/snowflake/api-docs/accountrole/
https://www.pulumi.com/registry/packages/snowflake/api-docs/role/

**Okta:**

https://www.pulumi.com/registry/packages/okta/api-docs/logstream/
https://www.pulumi.com/registry/packages/okta/api-docs/user/user/
https://www.pulumi.com/registry/packages/okta/api-docs/policy/ruleidpdiscovery/

**Rancher:**
https://www.pulumi.com/registry/packages/rancher2/api-docs/nodetemplate/


 Also, good to see you around @bschwedler 🙂
